### ISSUE TITLE
DIL packages wrong spacing

### ISSUE THREAD

**Issue by niclashoyer** [horizon-eda/horizon-pool#103]
I just noticed this while trying to place a generic pin header (e.g. 2x5) in line with a DIP package.

It seems that the DIP packages all have a pin spacing of 2.5 mm instead of 2.54 mm.

**Comment by atoav** [comment]
Good catch! I fixed it in my fork and all open PRs containing DIP packages already. Take this as a fix: https://github.com/carrotIndustries/horizon-pool/pull/85
