### ISSUE TITLE
Part for DC barrel Jack ?

### ISSUE THREAD

**Issue by chechu2k5** [horizon-eda/horizon-pool#147]
Hi! 

This isn't an issue/defect as much as a question ... I just started playing around with Horizon and was looking to make a simple circuit powered by a [5.5mm/2.1mm dc barrel jack (through hole)](https://www.sparkfun.com/products/119). I tried searching this repository but didn't land any hits for such a component. I also looked around in some of the other forks but didn't quite find what I was looking for. Is there one I might have missed ? 

(P.S) If this is not the correct way/place to ask for info on parts, please point me to the right place

![00119-03-L](https://user-images.githubusercontent.com/5258640/79056996-12356980-7c11-11ea-800c-00f9d7f00855.jpg)

**Comment by atoav** [comment]
I think you didn't miss it, but you are lucky: I wanted to make one of these anyways, so I might just do it now (well post the link to the PR here once it is done). Always make sure to check the Pull Requests over at the [horizon-pool repository](https://github.com/horizon-eda/horizon-pool/pulls).

If you are looking for audio related parts (jacks, specific audio ICs etc) the [work branch](https://github.com/atoav/horizon-pool/tree/work) of my pool-fork includes everything, that I made a PR for. Just make sure to check pinouts yourself to be sure – and if you did so, it would be amazing if you post your results to the fitting PR (_especially_ if you found an error, but if you verified a part or even verified it in production, that is even more valuable).

**Comment by atoav** [comment]
Update: Instead of using "generic" parts we always like it better if we can use something specific with a real MPN. I think [this Part from Würth](https://www.we-online.de/katalog/datasheet/6941xx301002.pdf) fits the generic counterparts pretty well & KiCAD happens to have an opensourced 3D model for it, so I will just make this one.

**Comment by chechu2k5** [comment]
Cool! Thanks for the pointer. I will check it out.

**Comment by atoav** [comment]
Update: The part is now available via PR #148 or in my forks work branch as mentioned above

**Comment by atoav** [comment]
If this fits your bill, kindly close this issue : )

**Comment by chechu2k5** [comment]
yes! thank you for the reminder. i'll close this issue
