### ISSUE TITLE
2.54mm generic pin headers off grid

### ISSUE THREAD

**Issue by niclashoyer** [horizon-eda/horizon-pool#178]
If I place the 2.54 mm generic pin headers on a 2.54 mm grid it seems that the pith of the headers is actually a bit wider than 2.54 mm. Is this on purpose?

![Bildschirmfoto von 2021-01-03 21-23-47](https://user-images.githubusercontent.com/175808/103488108-5fdeab80-4e0a-11eb-82a6-c24d0e142b0f.png)

**Comment by carrotIndustries** [comment]
> is actually a bit wider than 2.54 mm. Is this on purpose?

Measuring the spacing between pin 1 and 9 results in a pitch of 2.54mm. Can you you explain how you arrived at your conclusion?

**Comment by niclashoyer** [comment]
ah my bad. I had a grid spacing of 1.25 mm and so any other parts placed where off. I adjusted the grid spacing to 1.27 mm and everything is fine now :+1: thanks for the fast reply!
