### ISSUE TITLE
Parts made of multiple units

### ISSUE THREAD

**Issue by LHSmicius** [horizon-eda/horizon-pool#312]
Some people like to use parts made of single unit, some people like to split part into multiple units. Example in picture below, similar 64 pin MCU is splitted on left and as single unit on right.
![image](https://user-images.githubusercontent.com/46829407/224147551-48a6fc54-85c2-46e1-8979-f05f8b35078d.png)

It is not clear when part must be splitted or maybe pool should contain both versions of same part. If:
1. Part must be splitted. Then what are indicators that part must be splitted? E.x. Pin count, logical blocks...
2. Pool must contain both versions. Then how to mark them? Naming convention is needed (I think).

**Comment by carrotIndustries** [comment]
From my gut feeling about 100pins is the threshold where splitting entities into multiple gates makes sense.

Having both versions just causes confusion.

**Comment by RX14** [comment]
Logic gates and multiple opamps have the property that at the schematic level you don't care that they happen to be in the same package (which is not the case for an MCU). Anything that meets that criteria or is over 100 pins should be split.

**Comment by fruchti** [comment]
> Logic gates and multiple opamps have the property that at the schematic level you don't care that they happen to be in the same package (which is not the case for an MCU). Anything that meets that criteria or is over 100 pins should be split.

I like this framing. There have been [discussions about this previously](https://github.com/horizon-eda/horizon-pool-convention/issues/8), but I no longer think that handling that topic in this much detail is productive. A rule like this, which could be followed in spirit and not to the letter, would a good option.

I’d maybe add some sort of exception for electromechanical parts, e.g. relays, mechanically coupled switches, potentiometers. Maybe basing the decision on the typical use makes sense here—if the part ends up being unwieldy in a schematic as a single symbol, it has to be split.

**Comment by RX14** [comment]
I think rules which have a clear spirit instead of a lot of detail are easier to follow. Especially since there's no permanent consequences to getting anything "wrong" here. Things can always be changed later.

**Comment by fruchti** [comment]
I added a rule like this to the convention in https://github.com/horizon-eda/horizon-pool-convention/commit/083f92478184f9d80d83344fb599333de5eb1de1. Let me know if it isn’t clear enough or if I missed something here!
